services:
  db:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:/pg/tabel/pgdata
