# Локальные адреса
address=/mettem.lan/192.168.1.242
address=/www.mettem.lan/192.168.1.242

# Слушать всё, что приходит в контейнер
listen-address=0.0.0.0

# Включаем логи, чтобы в `docker logs` было видно, доходят ли запросы
log-queries

# Игнорируем внутренний resolv.conf контейнера
no-resolv

# КРИТИЧНО: DNS-серверы для остального интернета
server=8.8.8.8
server=1.1.1.1
